routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::group(['middleware' => 'new.auto'],
    function () {
        Route::resource('/new-auto', 'NewAutoUserController');
    });

Route::group([
    'prefix' => 'admin',
    'middleware' => 'admin',
    'namespace' => 'Admin'],
    function () {
        Route::get('/', 'AdminDashboardController@index')->name('admin.index');
        Route::resource('/parking', 'ParkingController');
        Route::resource('/auto', 'AutoController');
        Route::resource('/user', 'UserController');
    });

resources/views/page/create.blade.php
@extends('layouts.app')
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="container-fluid">
        <!-- Main content -->
        <div class="offset-1 col-md-10">
            <br>
            <form action="{{route('new-auto.store')}}" method="POST">
                @csrf
                <div class="box-header">
                    <h3>Добавление авто</h3>
                    @include('admin.errors')
                </div>
                <hr>
                <br>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-3">
                            <h5>Номер автомобиля</h5>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text"  class="form-control" value="{{old('number_cars')}}"
                                       name="number_cars">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <h5>Имя водителя</h5>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="{{old('driver_name')}}"
                                           name="driver_name">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="{{ route('new-auto.index') }}" class="btn btn-light">Назад</a>
                    <button class="btn btn-success pull-right">Добавить</button>
                </div>
                <!-- /.box-footer-->
            </form>
        </div>
        <!-- /.box -->

    </div>
    <!-- /.content-wrapper -->

@endsection

resources/views/page/edit.blade.php
@extends('layouts.app')
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="container-fluid">
        <!-- Main content -->
        <div class="offset-1 col-md-10">
            <br>
            <form action="{{route('new-auto.update', $auto->id)}}" method="POST">
                @csrf
                @method('PUT')
                <div class="box-header">
                    <h3>Редактирование авто</h3>
                    @include('admin.errors')
                </div>
                <hr>
                <br>
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-3">
                            <h5>Номер автомобиля</h5>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <input type="text"  class="form-control" value="{{$auto->number_cars}}"
                                       name="number_cars">
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-3">
                            <h5>Имя водителя</h5>
                        </div>
                        <div class="col-md-6">
                            <div class="form-group">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="{{$auto->driver_name}}"
                                           name="driver_name">
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.box-body -->
                <div class="box-footer">
                    <a href="{{ route('new-auto.index') }}" class="btn btn-light">Назад</a>
                    <input type="hidden" name="id" value="{{$auto->id}}">
                    <button class="btn btn-success pull-right">Изменить</button>
                </div>
                <!-- /.box-footer-->
            </form>
        </div>
        <!-- /.box -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/page/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="container-fluid">
        <div class="form-group">
            <a href="{{route('new-auto.create')}}" class="btn btn-success">Добавить авто</a>
        </div>
        <div class="box-header">
            @include('admin.errors')
        </div>
        <div class="row">
            <div class="offset-3 col-md-6">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">№</th>
                        <th scope="col">Номер авто</th>
                        <th scope="col">Имя водителя</th>
                        <th scope="col">Автопарки авто</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($res as $val)
                        <tr>
                            <th scope="row">{{$val['id']}}</th>
                            <td>{{$val['number_cars']}}</td>
                            <td>{{$val['driver_name']}}</td>
                            <td>
                                @foreach ($val['parking'] as $item)
                                    {{$item['name'] . ' / '}}
                                @endforeach
                            </td>
                            <td>
                            <div class="form-group">
                                <a href="{{route('new-auto.edit',$val['id'])}}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></a>
                            </div>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
@endsection