routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/', 'HomeController@index')->name('home');
Route::group(['middleware' => 'new.auto'],
    function () {
        Route::resource('/new-auto', 'NewAutoUserController');
    });

Route::group([
    'prefix' => 'admin',
    'middleware' => 'admin',
    'namespace' => 'Admin'],
    function () {
        Route::get('/', 'AdminDashboardController@index')->name('admin.index');
        Route::resource('/parking', 'ParkingController');
        Route::resource('/auto', 'AutoController');
        Route::resource('/user', 'UserController');
    });

app/Models/Parking.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Parking extends Model
{
    /**
     * @var string[]
     */
    protected $fillable = ['name','address', 'schedule'];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     */
    public function auto()
    {
        return $this->belongsToMany(
          Auto::class,
          'auto_parkings',
            'parking_id',
            'auto_id'
        );
    }

    /**
     * @param $fields
     * @return static
     * Добавление парковки
     */
    public static function add($fields)
    {
        $parking = new static();
        $parking->fill($fields);
        $parking->save();

        return $parking;
    }

    /**
     * @param $fields
     * Редактирование парковки
     */
    public function edit($fields)
    {
        $this->fill($fields);
        $this->save();
    }

    /**
     * @throws \Exception
     * Удаление парковки
     */
    public function remove()
    {
        $this->delete();
    }

    /**
     * @param $id
     * Сохранение авто к парковкам
     * принимаем массив из id [1,3,5,6 ....]
     */
    public function setAuto($id)
    {
        if ($id == null){return;}
        $this->auto()->sync($id);
    }

    /**
     * @param $query
     * @param $s
     * @return mixed
     */
    public function scopeSearch($query , $s)
    {
        $term = "%$s%";
        return $query->where('name','like', $term)
            ->orWhere('address', 'like', $term);
    }
}

app/Http/Controllers/Admin/ParkingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\AutoCreateValidator;
use App\Http\Requests\ParkingCreateValidator;
use App\Models\Parking;
use App\Repositories\ParkingRepository;
use App\Repositories\ParkingRepositoryInterface;

class ParkingController extends Controller
{

    /**
     * @var ParkingRepository
     */
    private $parkingRepository;

    /**
     * ParkingController constructor.
     * @param ParkingRepositoryInterface $parkingRepository
     */
    public function __construct(ParkingRepositoryInterface $parkingRepository)
    {
        $this->parkingRepository = $parkingRepository;
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $customers = $this->parkingRepository->allParking(10);
        return view('admin.parking.index', ['parking' => $customers,]);
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    function create()
    {
        return view('admin.parking.create');
    }

    /**
     * @param ParkingCreateValidator $request
     * @param Parking $parking
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(ParkingCreateValidator $request, Parking $parking)
    {
        $forms = $request->only('name', 'address', 'schedule');
        $result = $parking::add($forms);
        if (!$result) {
            return back()->withErrors(['msg' => 'Ошибка создания!'])->withInput();
        } else {
            return redirect()->route('parking.index')->with(['success' => 'Запись успешно создана']);
        }
    }

    /**
     * @param $id
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $avtopark = $this->parkingRepository->findById($id);
        return view('admin.parking.edit', ['avtopark' => $avtopark]);
    }

    /**
     * @param ParkingCreateValidator $request
     * @param AutoCreateValidator $autoCreateValidator
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(ParkingCreateValidator $request, AutoCreateValidator $autoCreateValidator, $id)
    {
        $forms = $request->only('name', 'address', 'schedule');
        $result = $this->parkingRepository->findById($id);
        $auto = $this->parkingRepository->addNewAuto($id);
        if ($auto) {return back()->with(['success'=>'']);}
        $result->edit($forms);
        if (!$result) {
            return back()->withErrors(['msg' => 'Ошибка обновления!'])->withInput();
        } else {
            return back()->with(['success' => 'Запись успешно обновлена']);
        }
    }

    /**
     * @param $id
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy($id)
    {
        $result = $this->parkingRepository->delete($id);
        if (!$result) {
            return back()->withErrors(['msg' => 'Ошибка удаления!'])->withInput();
        } else {
            return redirect()->route('parking.index')->with(['success' => 'Запись успешно удалена']);
        }
    }
}

resources/views/admin/parking/create.blade.php
@extends('admin.layout')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">
                <form action="{{route('parking.store')}}" method="POST">
                    @csrf
                    <div class="box-header">
                        <h3>Автопарк</h3>
{{--                        @include('admin.errors')--}}
                        {{--                        <div class="col-md-12 alert alert-success" role="alert"></div>--}}
                    </div>
                    <div class="box-body">
                        <div class="row">
                            <div class="col-md-3">
                                <h5>Название</h5>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group{{$errors->has('name') ? 'has-error' : ''}}">
                                    <input type="text" id="name" class="form-control" value="{{old('name')}}"
                                           name="name">
                                    @if ($errors->has('name'))
                                        <span class="help-block">
                                          <strong style="color: red">{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <h5>Адрес</h5>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <div class="form-group{{$errors->has('address') ? 'has-error' : ''}}">
                                        <input type="text" id="address" class="form-control" value="{{old('address')}}"
                                               name="address">
                                        @if ($errors->has('address'))
                                            <span class="help-block">
                                          <strong style="color: red">{{ $errors->first('address') }}</strong>
                                        </span>
                                        @endif
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <h5>График работы</h5>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" id="schedule" class="form-control" value="{{old('schedule')}}"
                                           name="schedule">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <h3>Машины</h3>
                                <hr>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-10 col-md-push-1">
                                <table class="table table-dark information_json">
                                    <tr>
                                        <th><h5>Номер автомобиля</h5></th>
                                        <th><h5>Имя водителя</h5></th>
                                    </tr>
                                    <tr class="information_json_plus">
                                        <td></td>
                                        <td></td>
                                        <td><span class="btn btn-success plus pull-right">+</span></td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    <div class="box-footer">
                        <a href="{{ route('parking.index') }}" class="btn btn-default">Назад</a>
                        <button class="btn btn-success pull-right">Добавить</button>
                    </div>
                    <!-- /.box-footer-->
                </form>
            </div>
            <!-- /.box -->

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection

resources/views/admin/parking/edit.blade.php
@extends('admin.layout')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">
            <!-- Default box -->
            <div class="box">
                <div class="box-header">
                    <h3>Редактирование автопарки {{$avtopark->name}}</h3>
                    @include('admin.errors')
                </div>
                <div class="box-body container-fluid">
                    <form action="{{ route('parking.update',$avtopark->id) }}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="col-md-3">
                                <h5>Название</h5>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="{{$avtopark->name}}" name="name">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <h5>Адрес</h5>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="{{$avtopark->address}}"
                                           name="address">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3">
                                <h5>График работы</h5>
                            </div>
                            <div class="col-md-6">
                                <div class="form-group">
                                    <input type="text" class="form-control" value="{{$avtopark->schedule}}"
                                           name="schedule">
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <h3>Автомобили автопарка</h3>
                                <hr>
                            </div>
                            <div class="row">
                                <div class="col-md-8 col-md-push-2">
                                    <table class="table information_json">
                                        <tr>
                                            <th><h5>Номер автомобиля</h5></th>
                                            <th><h5>Имя водителя</h5></th>
                                        </tr>
                                        <tr class="information_json_plus">
                                            <td></td>
                                            <td></td>
                                            <td><span class="btn btn-success plus pull-right">+</span></td>
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                        <div class="box-footer">
                            <input type="hidden" name="id" value="{{$avtopark->id}}">
                            <a href="{{ route('parking.index') }}" class="btn btn-default">Назад</a>
                            <button type="submit" class="btn btn-warning pull-right">Изменить</button>
                        </div>
                    </form>
                    <!-- /.box-footer-->
                    <div class="col-xs-12 col-md-10 col-xl-10 col-lg-8 col-md-push-2">
                        <table class="table table-hover">
                            <thead>
                            <tr>
                                <th>Номер автомобиля</th>
                                <th>Имя водителя</th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(!empty($avtopark->auto))
                                @foreach($avtopark->auto as $item)
                                    <tr>
                                        <form action="{{ route('auto.update',$item->id) }}" method="POST">
                                            @csrf
                                            @method('PUT')
                                        <td><input type="text" name="number_cars" class="form-control"
                                                   value="{{$item->number_cars}}"></td>
                                        <td><input type="text" name="driver_name" class="form-control"
                                                   value="{{$item->driver_name}}"></td>
                                        <td>
                                            <input type="hidden" name="id" value="{{$item->id}}">
                                            <button type="submit" class="btn btn-success pull-right">Обновить</button>
                                        </td>
                                        </form>
                                        <td>
                                            <form action="{{ route('auto.update',$item->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                            <button type="submit" onclick="return confirm('Вы точно хотите удалить данный автомобиль ?')" class="btn btn-danger pull-right">X</button>
                                            </form>
                                        </td>
                                    </tr>
                                @endforeach
                            @endif
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->

@endsection

resources/views/admin/parking/index.blade.php
@extends('admin.layout')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Main content -->
        <section class="content">

            <!-- Default box -->
            <div class="box">
                <div class="box-header">
                    <h3>Список автопарков</h3>
                    @include('admin.errors')
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="col-md-3">
                                <div class="form-group">
                                    <a href="{{route('parking.create')}}" class="btn btn-success">Добавить</a>
                                </div>
                            </div>
                            <div class="col-md-6 col-md-push-4">
                                <form action="{{ route('parking.index') }}" method="GET" class="form-inline">
                                    <div class="form-group">
                                        <input type="text" class="form-control" name="s" placeholder="Поиск">
                                    </div>
                                    <div class="form-group">
                                        <button type="submit" class="btn btn-primary">Search</button>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <table id="example1" class="table table-bordered table-striped">
                        <thead>
                        <tr>
                            <th>№</th>
                            <th>Название</th>
                            <th>Адрес</th>
                            <th>График работы</th>
                            <th>Действия</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($parking as $item)
                            <tr>
                                <td>{{$item['id']}}</td>
                                <td><a href="{{route('parking.edit', $item['id'])}}">{{$item['name']}}</a></td>
                                <td>{{$item['address']}}</td>
                                <td>{{$item['address']}}</td>
                                <td><a href="{{route('parking.edit', $item['id'])}}"><i class="fa fa-edit"
                                                                                         title="Редакировать"></i></a>
                                    <form action="{{ route('parking.destroy',$item['id']) }}" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button onclick="return confirm('Вы точно желаете удалить данную автопарковку?')"
                                                type="submit" class="btn btn-danger btn-sm">
                                            <i class="fa fa-trash" title="Удалить" aria-hidden="true"></i>
                                        </button>
                                    </form>
                                </td>
                            </tr>
                        @endforeach

                        </tbody>
                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
            {{ $parking->links() }}

        </section>
        <!-- /.content -->
    </div>
    <!-- /.content-wrapper -->
@endsection